permalink:           pretty

title:               'Rants'
tagline:             'and maybe some other things.'
gems:
  - jekyll-paginate
paginate:            5
paginate_path:       rants

author:
  name:              Adam Michael
  url:               https://ajmichael.net
  email:             adam@ajmichael.net

version:             1.0.0
